import { Clock3, GitBranch, MessageCircle, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { AuthUser } from "@/features/auth/types/auth";
import { canCancelTicket, canChangeTicketStatus, canEditTicket, canViewAssignmentHistory } from "../utils/ticketPermissions";
import { TICKET_STATUSES, type Ticket, type TicketStatus } from "../types/ticket";

export function TicketTable({ tickets, user, pending, onEdit, onCancel, onConversation, onHistory, onWorkflow, onStatus }: { tickets: Ticket[]; user: AuthUser | null; pending: boolean; onEdit: (ticket: Ticket) => void; onCancel: (ticket: Ticket) => void; onConversation: (ticket: Ticket) => void; onHistory: (ticket: Ticket) => void; onWorkflow: (ticket: Ticket) => void; onStatus: (ticket: Ticket, status: TicketStatus) => void }) {
  if (tickets.length === 0) return <div className="py-20 text-center"><p className="font-medium">No tickets found</p><p className="mt-1 text-sm text-muted-foreground">Create a ticket or adjust the current filters.</p></div>;
  return <div className="overflow-x-auto"><table className="w-full min-w-4xl text-left text-sm"><thead className="border-b bg-muted/40 text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Ticket</th><th className="px-5 py-3">Category</th><th className="px-5 py-3">Priority</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{tickets.map((ticket) => <tr className="hover:bg-muted/25" key={ticket.id}><td className="max-w-sm px-5 py-4"><p className="font-medium">{ticket.title}</p><p className="mt-1 text-xs text-muted-foreground">{ticket.referenceNumber} · {new Date(ticket.createdAtUtc).toLocaleDateString()}</p></td><td className="px-5 py-4">{ticket.category === "AccessRequest" ? "Access Request" : ticket.category}</td><td className="px-5 py-4"><span className={cn("rounded-full px-2 py-1 text-xs font-medium", ticket.priority === "Critical" ? "bg-destructive/10 text-destructive" : ticket.priority === "High" ? "bg-amber-500/10 text-amber-700" : "bg-muted text-muted-foreground")}>{ticket.priority}</span></td><td className="px-5 py-4">{canChangeTicketStatus(user, ticket) ? <select aria-label="Ticket status" className="h-8 rounded-lg border bg-background px-2 text-xs" disabled={pending} value={ticket.status} onChange={(event) => onStatus(ticket, event.target.value as TicketStatus)}>{TICKET_STATUSES.map((status) => <option key={status} value={status}>{status.replace(/([A-Z])/g, " $1").trim()}</option>)}</select> : <span className="text-xs font-medium">{ticket.status.replace(/([A-Z])/g, " $1").trim()}</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><Button aria-label="Comments and attachments" onClick={() => onConversation(ticket)} size="icon-sm" variant="ghost"><MessageCircle /></Button>{canViewAssignmentHistory(user) && <Button aria-label="Workflow" onClick={() => onWorkflow(ticket)} size="icon-sm" variant="ghost"><GitBranch /></Button>}<Button aria-label="History" onClick={() => onHistory(ticket)} size="icon-sm" variant="ghost"><Clock3 /></Button>{canEditTicket(user, ticket) && <Button aria-label="Edit" onClick={() => onEdit(ticket)} size="icon-sm" variant="ghost"><Pencil /></Button>}{canCancelTicket(user, ticket) && <Button aria-label="Cancel ticket" onClick={() => onCancel(ticket)} size="icon-sm" variant="destructive"><Trash2 /></Button>}</div></td></tr>)}</tbody></table></div>;
}
