IF DB_ID(N'$(DB_NAME)') IS NULL
BEGIN
    EXEC(N'CREATE DATABASE [$(DB_NAME)]');
END
GO
IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = N'$(DB_APP_USER)')
BEGIN
    CREATE LOGIN [$(DB_APP_USER)] WITH PASSWORD = '$(DB_APP_PASSWORD)';
END
GO
USE [$(DB_NAME)];
GO
IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'$(DB_APP_USER)')
BEGIN
    CREATE USER [$(DB_APP_USER)] FOR LOGIN [$(DB_APP_USER)];
END
GO
ALTER ROLE db_owner ADD MEMBER [$(DB_APP_USER)];
GO
